---
horizon_url: "http://9.30.217.9"

auth: {
  auth_url: "http://9.30.217.9:5000/v3",
  username: "demo",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "demo"
}

app_env: {
  target_os: "ubuntu",
  image_name: "ubuntu-16.04",
  region_name: "RegionOne",
  availability_zone: "nova",
  validate_certs: False,
  ssh_user: "ubuntu",
  private_net_name: "demonet",
  flavor_name: "m1.medium",
  public_key_file: "/home/ubuntu/.ssh/interop.pub",
  private_key_file: "/home/ubuntu/.ssh/interop",
  stack_size: 3,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  flannel_backend: { "Type": "udp", "Port": 8285 },
  flannel_repo: "https://github.com/coreos/flannel/releases/download/v0.7.0/flannel-v0.7.0-linux-amd64.tar.gz",
  etcd_repo: "https://github.com/coreos/etcd/releases/download/v2.2.5/etcd-v2.2.5-linux-amd64.tar.gz",
  k8s_repo: "https://storage.googleapis.com/kubernetes-release/release/v1.5.0/bin/linux/amd64/"
}
