---
- name: Haproxy install
  package:
    name: haproxy
    state: latest

- name: Enable haproxy service
  replace:
    dest: /etc/default/haproxy
    regexp: "ENABLED=0"
    replace: "ENABLED=1"
    backup: no
  when: ansible_distribution == 'Ubuntu'

- name: Modify haproxy configuration
  blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    insertafter: EOF
    block: |
      frontend http-in
          bind *:80
          default_backend backend_servers
          option forwardfor

      backend backend_servers
          balance     roundrobin

- name: Add web servers to the haproxy
  lineinfile:
    dest: /etc/haproxy/haproxy.cfg
    line: "    server ws{{ item[0].openstack[item[1]] }} {{ item[0].openstack[item[1]] }}:80 check"
  with_nested:
    - "{{ hostvars.cloud.webserver.results }}"
    - ["private_v4", "public_v4"]
  when: item[0].openstack[item[1]] != ''
  no_log: True

- service: name=haproxy state=restarted enabled=yes
