---
- name: Add the node to host group with private IP
  add_host:
    name: "{{ hostvars[item].public_ip }}"
    inter_ip: "{{ hostvars[item].private_ip }}"
    inter_name: "{{ item }}"
    groups: "{{ hostvars[item].targetgroup }}"
  with_items: "{{ groups['prohosts'] }}"

- name: Add one web server to wps host group
  add_host:
    name: "{{ groups['webservers'][0] }}"
    groups: wps
  no_log: True

- name: Remove the lampstackhosts file
  file:
    path: "{{ playbook_dir }}/run/lampstackhosts"
    state: absent

- name: Build up hosts file
  lineinfile:
    dest: "{{ playbook_dir }}/run/lampstackhosts"
    line: "{{ hostvars[item].inter_ip }} {{ hostvars[item].inter_name }}"
    state: present
    create: yes
  with_flattened:
    - '{{ groups["dbservers"] }}'
    - '{{ groups["balancers"] }}'
    - '{{ groups["webservers"] }}'

- name: Wait until servers are up and runnning
  wait_for:
    host: "{{ item }}"
    port: 22
    state: started
    delay: 15
    connect_timeout: 20
    timeout: 300
  with_items:
    - '{{ groups["dbservers"] }}'
    - '{{ groups["balancers"] }}'
    - '{{ groups["webservers"] }}'

