---
- name: Delete key pairs
  os_keypair:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: "lampstack"
    public_key_file: "{{ app_env.public_key_file }}"

- name: Delete security group
  os_security_group:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: lampstack_sg
    description: secuirty group for lampstack

- name: Delete cinder volume
  os_volume:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    wait: yes
    display_name: db_volume
