---
- name: Add database node to provisioning host group
  add_host:
    name: "database"
    targetgroup: "dbservers"
    ansible_host: "127.0.0.1"
    groups: "prohosts"
  no_log: True

- name: Add balancer node to provisioning host group
  add_host:
    name: "balancer"
    targetgroup: "balancers"
    ansible_host: "127.0.0.1"
    groups: "prohosts"
  no_log: True

- name: Add apache nodes to provisioning host group
  add_host:
    name: "apache-{{ item }}"
    targetgroup: "webservers"
    ansible_host: "127.0.0.1"
    groups: "prohosts"
  with_sequence: count={{ app_env.stack_size - 2 }}
  no_log: True
