---
horizon_url: "http://9.30.217.9"

auth: {
  auth_url: "http://9.30.217.9:5000/v3",
  username: "demo",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "demo"
}

app_env: {
  image_name: "ubuntu-14.04",
  region_name: "RegionOne",
  availability_zone: "nova",
  validate_certs: False,
  ssh_user: "ubuntu",
  private_net_name: "demonet",
  flavor_name: "m1.large",
  public_key_file: "/home/ubuntu/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  wp_latest: "https://wordpress.org/wordpress-4.6.tar.gz",
  wp_theme: "https://downloads.wordpress.org/theme/iribbon.2.0.65.zip",
  wp_posts: "https://salesdemo-sjc-swift.openstack.blueboxgrid.com:8090/v1/0de866ff4f78495599e66db3580462d0/Interop/postsxml.zip"
}
