---
##############################################################################
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  remote_user: root
  max_fail_percentage: 0
  tasks:
    - name: pull OPNFV Opera code
      git:
        repo: https://github.com/opnfv/opera.git
        dest: /home/opera
        update: yes

    - name: config admin-openrc.sh
      file:
        src: admin-openrc.sh
        dest: /home/opera/conf/admin-openrc.sh

    - name: pull OPNFV Functest docker image to test vIMS
      docker_image:
        name: opnfv/functest:latest

    - name: deploy OPEN-O and vIMS
      shell: /home/opera/opera_launch.sh > opera.log
      args:
        chdir: /home/opera
        creates: opera.log
      async: 0
      poll: 60

    - name: create openstack.creds
      shell: cp /home/opera/conf/admin-openrc.sh /home/opera/conf/openstack.creds

    - name: remove OPNFV Functest docker container
      command: "docker rm -f functest-opera"

    - name: run OPNFV Functest docker container
      command: "docker run -id
              -v /home/opera/conf/openstack.creds:/home/opnfv/functest/conf/openstack.creds
              --name=functest-opera
              opnfv/functest:latest /bin/bash"

    - name: start OPNFV Functest docker container
      command: "docker start functest-opera"

    - name: test vIMS via OPNFV Functest
      command: "grep 'Duration' /home/opera/opera.log"
      register: grep_out
      until: grep_out.stdout.find("Duration")!=-1
      retries: 60
      delay: 120

    - name: run vIMS test on OPNFV Functest
      command: docker exec functest-opera python /home/opnfv/repos/functest/functest/ci/run_tests.py -t opera_ims
