---
- name: Install python2 for Ansible
  raw: dnf install -y python2 python2-dnf libselinux-python
  register: result
  until: result|success

- name: Set SELinux to permisive
  selinux: policy=targeted state=permissive

- name: Setup /etc/hosts on every node
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
  with_lines: cat "{{ playbook_dir }}/run/lampstackhosts"