---
- name: Setup /etc/hosts on every node
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
    state: present
  with_lines: cat "{{ playbook_dir }}/run/lampstackhosts"

- name: Make sure that cloud-init script has completed
  wait_for:
    path: "/run/cloud-init/result.json"
