---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"
  tags: "info"

- name: provision servers
  hosts: cloud
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - "{{ action }}"
  tags: "{{ action }}"

- name: Wait for servers to be up running
  hosts: cloud
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/ready/tasks/{{ action }}.yml"
  roles:
    - ready
  tags: "{{ action }}"

- name: Install required packages for all nodes
  hosts: workers, masters
  gather_facts: true
  user: "{{ app_env.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/common/tasks/{{ app_env.target_os }}.yml"
  roles:
    - common
  environment: "{{ proxy_env }}"
  tags: "common"

- name: Setup master
  hosts: masters
  gather_facts: true
  user: "{{ app_env.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/master/tasks/{{ app_env.target_os }}.yml"
  roles:
    - master
  environment: "{{ proxy_env }}"
  tags: "master"

- name: Setup workers
  hosts: workers
  gather_facts: true
  user: "{{ app_env.ssh_user }}"
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  tasks:
    - include: "roles/worker/tasks/{{ app_env.target_os }}.yml"
  roles:
    - worker
  environment: "{{ proxy_env }}"
  tags: "worker"

- name: Inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          Access kubernetes at
          http://{{ groups['masters'][0] }}.
      when: groups['masters'] is defined
    - debug:
        msg: >-
          The work load test started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}
  tags: "info"