---
- name: Get start timestamp
  set_fact: starttime="{{ ansible_date_time }}"

- name: Delete key pairs
  os_keypair:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: "k8s"
    public_key_file: "{{ app_env.public_key_file }}"

- name: Destroy master node
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: master
    image: "{{ app_env.image_name }}"
    key_name: "k8s"
    timeout: 200
    network: "{{ app_env.private_net_name }}"
    meta:
      hostname: master

- name: Destroy worker nodes
  os_server:
    state: "absent"
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: worker-{{ item }}
    image: "{{ app_env.image_name }}"
    key_name: "k8s"
    timeout: 200
    network: "{{ app_env.private_net_name }}"
    meta:
      hostname: worker-{{ item }}
  with_sequence: count={{ app_env.stack_size - 1 }}

- name: Delete security group
  os_security_group:
    state: absent
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    name: k8s_sg
    description: secuirty group for lampstack
