---
- os_floating_ip:
    auth: "{{ auth }}"
    region_name: "{{ app_env.region_name }}"
    availability_zone: "{{ app_env.availability_zone }}"
    validate_certs: "{{ app_env.validate_certs }}"
    state: absent
    floating_ip_address: "{{ item }}"
    server: "{{ hostvars[item].inter_name }}"
  with_flattened:
    - "{{ groups['webservers'] }}"
    - "{{ groups['dbservers'] }}"
  no_log: True
