---
- name: Wait until servers are up and runnning
  wait_for:
    host: "{{ item }}"
    port: 22
    state: started
    delay: 15
    connect_timeout: 20
    timeout: 300
  with_items: "{{ groups['workers'] }}"